remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: 'Being a Rubbish in bioinformatics'
description: description: "I am studying some basic programming languages like C++, Python, and R. \
Some techniques like statistical analyzing and machine learning are also my interests. \
I am aiming to be a rubbish in this field! \
$$\int_{-\infty}^{\infty} \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x-\mu)^2}{2\sigma^2}} \,dx = 1$$"